// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxIwIJ3rtScWVbveBpYgE0Pa1yLcL0OkA',
    appId: '1:718245008452:web:d8900e2906a06182bcd811',
    messagingSenderId: '718245008452',
    projectId: 'fotoupdate-9651d',
    authDomain: 'fotoupdate-9651d.firebaseapp.com',
    databaseURL: 'https://fotoupdate-9651d-default-rtdb.firebaseio.com',
    storageBucket: 'fotoupdate-9651d.appspot.com',
    measurementId: 'G-FW81CHGT8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgwKC9J5RwZRdhNDZ8UiIBqZCwCzrxjc8',
    appId: '1:718245008452:android:d778838206eb369dbcd811',
    messagingSenderId: '718245008452',
    projectId: 'fotoupdate-9651d',
    databaseURL: 'https://fotoupdate-9651d-default-rtdb.firebaseio.com',
    storageBucket: 'fotoupdate-9651d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpBuKjD35F4jFXdW6fC5FSOpoMNORknc0',
    appId: '1:718245008452:ios:45288b233bba3d38bcd811',
    messagingSenderId: '718245008452',
    projectId: 'fotoupdate-9651d',
    databaseURL: 'https://fotoupdate-9651d-default-rtdb.firebaseio.com',
    storageBucket: 'fotoupdate-9651d.appspot.com',
    iosClientId: '718245008452-e77nje90g185qb0in6pt9nkt9k98kodc.apps.googleusercontent.com',
    iosBundleId: 'com.botanik.botanikBahcem',
  );
}
