// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvsftQWN99iQ9ILLTMTEJEQoqv-htmuuY',
    appId: '1:404197108359:web:28b50c00fce22a0c52a622',
    messagingSenderId: '404197108359',
    projectId: 'botanikbahcem',
    authDomain: 'botanikbahcem.firebaseapp.com',
    storageBucket: 'botanikbahcem.appspot.com',
    measurementId: 'G-7GP21GF939',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5srV3Qwzxj0e-QXS1EoGPGxa8YKhnxvw',
    appId: '1:404197108359:android:5d72b463f4333ee452a622',
    messagingSenderId: '404197108359',
    projectId: 'botanikbahcem',
    storageBucket: 'botanikbahcem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwbdhRsDKsxUwRLjiD6V0XlzF9O9TTdH0',
    appId: '1:404197108359:ios:c95948bd9af6297652a622',
    messagingSenderId: '404197108359',
    projectId: 'botanikbahcem',
    storageBucket: 'botanikbahcem.appspot.com',
    iosClientId: '404197108359-r3kmr56o93heo82bo2cvkg7q49lfnnnr.apps.googleusercontent.com',
    iosBundleId: 'com.botanik.botanikBahcem',
  );
}
